### PR TITLE
CAPA: Release v29.3.1. 

### PR DESCRIPTION
**Pull request by paurosello**
### Checklist

- [ ] Roadmap issue created
- [ ] Release uses latest stable Flatcar
- [ ] Release uses latest Kubernetes patch version

### Triggering E2E tests

To trigger the E2E test for each new Release added in this PR, add a comment with the following:

`/run releases-test-suites`

If you want to trigger conformance tests, you can do so by adding a comment similar to the following:

`/run conformance-tests PROVIDER=capa RELEASE_VERSION=29.1.0`

For more details see the [README.md](/README.md#running-tests-against-prs).

### CODE REVIEW

**Review by alex-dabija — APPROVED** [review]

**Review by AndiDog — APPROVED** [review]

**Comment by Gacko** [comment]
This release will definitely roll nodes and we agreed on not doing patch releases which roll nodes...

**Comment by alex-dabija** [comment]
> This release will definitely roll nodes and we agreed on not doing patch releases which roll nodes...

It shouldn't. The two commits that are important between v2.3.0 and v2.4.0 of cluster-aws don't change anything for existing cluster nodes:
* [commit one](https://github.com/giantswarm/cluster-aws/commit/8285d7804c8cb01dc46b9892b9b7708596484a03#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR12) adds new tags to machine pools and the control plane if they are specified (no impact for existing clusters);
* [commit two](https://github.com/giantswarm/cluster-aws/commit/1edbb92195d852c07c9c0deb858ed45bf48fe2a4) doesn't render the subnet tags if the list is empty (it impacts only the subnets and not the nodes).
But, I might have missed something.

Could you explain why you think the release would roll the nodes? 

Yes, I agree that based on adding a new feature the release should have been a minor. We'll try do do better next time.

**Comment by Gacko** [comment]
The machine template is changing. Therefore it's hash is changing. And therefore the nodes are rolling. Also you're upgrading from v2.2.0 to v2.4.0, not from v2.3.0.

Last but not least this repository requires a codeowner review, which is Tenet. So I assume you force merged this.

**Comment by alex-dabija** [comment]
> The machine template is changing.

I forgot about the hash changing.

> Also you're upgrading from v2.2.0 to v2.4.0, not from v2.3.0.

Yes, correct. There are more changes that I didn't look into.

> Last but not least this repository requires a codeowner review, which is Tenet. So I assume you force merged this.

I don't know about this.

**Comment by Gacko** [comment]
Also the included `cluster` chart changed and there are changes in there which might probably lead to node rolling. 🙂

**Pull request merged**
