### PR TITLE
CAPA: Release v29.4.0.

### PR DESCRIPTION
**Pull request by paurosello**
### Checklist

- [x] Roadmap issue created
- [x] Release uses latest stable Flatcar
- [x] Release uses latest Kubernetes patch version

### Triggering E2E tests

To trigger the E2E test for each new Release added in this PR, add a comment with the following:

`/run releases-test-suites`

If you want to trigger conformance tests, you can do so by adding a comment similar to the following:

`/run conformance-tests PROVIDER=capa RELEASE_VERSION=29.1.0`

For more details see the [README.md](/README.md#running-tests-against-prs).

### CODE REVIEW

**Comment by paurosello** [comment]
I don't like that we are forced to introduce a breaking change on a minor...

As phoenix we have introduced a new feature in cluster-aws which resulted in a minor release (2.4.0) and wanted to make a minor release (29.4.0) but due to the requirements from other teams we now have a breaking change.

Any thoughts? Why is there a breaking change introduced in 29.4.0 and not 30.0.0?

**Review by Gacko — CHANGES_REQUESTED** [review]
We already have an issue open for that. Please do not just change the requests as team added their requirements there for reasons. :)

**Comment by fiunchinho** [comment]
> We already have an issue open for that. Please do not just change the requests as team added their requirements there for reasons. :)

I think this was agreed on in Slack by both shield and tenet https://gigantic.slack.com/archives/C02FL4EAADD/p1731409971562999

**Comment by paurosello** [comment]
> We already have an issue open for that. Please do not just change the requests as team added their requirements there for reasons. :)

I checked with both teams involved and we agreed on making this change 

https://gigantic.slack.com/archives/C02FL4EAADD/p1731409971562999

**Comment by Gacko** [comment]
Can we please have the change in requests outside of this PR and also synced across all providers then? Also I'd appreciate if we could do releases with the bump in `observability-bundle` across all providers and not just CAPA. I know, this release might be important to you as you'd like to ship a feature for CAPA only, but if every team would come up with a new workload cluster release every time they release one of their apps, customers will probably never catch up with the latest releases and therefore get a consistent product experience, especially if the app versions differ across providers.

The latter probably hits us as Giant Swarm harder than the customers, as they normally only run on one provider, but this also is changing with hybrid MCs right now and so I think it's important for us who support the product to have customers use the same app versions across providers.

Apart from that we'd really appreciate to keep the content of a release in sync with previous releases. We never put a lot of details about Kubernetes or Flatcar releases into the `README.md` of CAPI releases. We usually just put links to the upstream changelog in there.

If you allow I'd like to extract the change in `requests.yaml` into a separate PR, push some suggestions to this PR and also come up with releases for CAPZ and CAPV.

**Comment by paurosello** [comment]
I will put this on hold and release 29.3.1 as we need a release today to make an installation with the changes to cluster-aws only

**Review by Gacko — CHANGES_REQUESTED** [review]
Basically LGTM, but please consider merging https://github.com/giantswarm/releases/pull/1492 first.

**Review by AndiDog — APPROVED** [review]

**Pull request merged**
