### PR TITLE
Use latest aws-operator 8.2.2-dev in wip version 11.1.1

### PR DESCRIPTION
**Pull request by corest**

### CODE REVIEW

**Comment by calvix** [comment]
isnt 11.1.1 used for something @paurosello ?

**Comment by paurosello** [comment]
Yes, there are 2 cluster in IC Consult.

We are going to need a new version with the updated net-exporter version.
Preferably without changing the AWS operator so we don't have to roll
nodes...


What do you think?

**Comment by corest** [comment]
It is in WIP, so I'm updating it. If it is not a wip anymore, why isn't it active?

**Comment by paurosello** [comment]
We don't want it to be active in all customers, can't we have another WIP
version?

**Comment by corest** [comment]
> We don't want it to be active in all customers, can't we have another WIP version?

**Comment by corest** [comment]
> We don't want it to be active in all customers, can't we have another WIP version?

We probably can. But then releasing team needs to add new wip release and announce that `11.1.1` should stay untouched and unreleased. Release message here https://gigantic.slack.com/archives/C90BZMUJ1/p1584440819128100 doesn't mention this. Also after adding new wip and then releasing it - previous one will become deprecated and visible for all the other customers

**Comment by paurosello** [comment]
Then could we at least change this version to 11.1.2?

IC Consult has two clusters in 11.1.0 and two with 11.1.1 and I will be upgrading them. No need to add 11.1.0 and 11.1.1 to master, will create a branch to fix all the mess.

**Pull request closed without merging**
