### PR TITLE
AWS v17.4.0

### PR DESCRIPTION
**Pull request by njuettner**
Issue: https://github.com/giantswarm/roadmap/issues/1081

### CODE REVIEW

**Comment by uvegla** [comment]
@njuettner I prepared this release just this morning: https://github.com/giantswarm/releases/pull/990 Can we please merge the two somehow? I really want to push app-operator and chart-operator of those versions exactly out.

**Review by uvegla — CHANGES_REQUESTED** [review]
We need to resolve with https://github.com/giantswarm/releases/pull/990

**Comment by njuettner** [comment]
@uvegla 👋🏻, sure we can merge everything into one 🙂. Phoenix planned to release v17.4.0 mainly because of some bigger changes, I haven't seen your PR sorry about that.

Would it be ok for you if we put all your changes into v17.4.0? Usually we plan all the upcoming releases here https://github.com/orgs/giantswarm/projects/273.

**Review by uvegla — APPROVED** [review]
Perfect, thanks a lot! Closed the other one. :)

**Comment by njuettner** [comment]
@ubergesundheit sure no problem, can you update it?

**Comment by ubergesundheit** [comment]
> @ubergesundheit sure no problem, can you update it?

I have experimented with `devctl release create` but there are some differences. I already modified the flags to match the yaml in this branch, but there are still changes in the README and also I cannot add `webhook-exporter`.

Should I just push my changes (minus the removal of `webhook-exporter` in my files) ?

```
devctl release create --name v17.4.0 --provider aws --base v17.3.3 --component aws-operator@11.15.0 --component cluster-operator@4.3.0 --component app-operator@5.12.0 --component aws-cni@1.11.2-nftables --component containerlinux@3139.2.2 --component kubernetes@1.22.11 --app external-dns@2.14.0@0.11.0 --app chart-operator@2.24.0 --app node-exporter@1.12.0@1.3.1 --app vertical-pod-autoscaler@2.4.0 --app metrics-server@1.7.0@0.5.2 --app cert-manager@2.15.0@1.7.3 --app aws-ebs-csi-driver@2.14.0@1.6.2 --app cluster-autoscaler@1.22.2-gs7 --overwrite
```

**Comment by kubasobon** [comment]
Can we update to the latest app-operator as well? `v6.0.1` was already tested by @pipo02mix in https://github.com/giantswarm/giantswarm/issues/22569.

**Review by T-Kukawka — APPROVED** [review]

**Pull request merged**
