### PR TITLE
aws v15.2.0 release

### PR DESCRIPTION
**Pull request by paurosello**

### CODE REVIEW

**Comment by calvix** [comment]
wtf, if I run `awscnf` manually it always works but here it always fail

**Comment by calvix** [comment]
Ready from my side

**Review by njuettner — APPROVED** [review]
lgtm

**Comment by calvix** [comment]
conformance test is not happy, but manually executed awscnf worked so this si some hiccup, feel free to  write release announcement and merge @alex-dabija

**Pull request merged**
