### PR TITLE
Update requests.yaml

### PR DESCRIPTION
**Pull request by QuentinBisson**
### Checklist
- [ ] Roadmap issue created
- [ ] Release uses latest stable Flatcar
- [ ] Release uses latest Kubernetes patch version

### CODE REVIEW

**Comment by T-Kukawka** [comment]
@QuentinBisson i saw issues with `version: ">= 0.1.9"` in your team channel

**Comment by QuentinBisson** [comment]
Good thing I tested it right? :(

**Comment by QuentinBisson** [comment]
I'll investigate tomorrow but this looks like a false issue

**Comment by QuentinBisson** [comment]
@T-Kukawka this is race condition between pmo and existing version of the bundle. As it's not installed yet, we can go ahead with it ;)

**Comment by QuentinBisson** [comment]
@T-Kukawka and @giantswarm/team-atlas can I get a look? Thank you

**Review by T-Kukawka — APPROVED** [review]

**Comment by QuentinBisson** [comment]
Thanks TK :)

**Pull request merged**
