### PR TITLE
add aws release 19.3.1

### PR DESCRIPTION
**Pull request by whites11**
### Checklist
- [ ] Roadmap issue created
- [ ] Release uses latest stable Flatcar
- [ ] Release uses latest Kubernetes patch version

### CODE REVIEW

**Comment by whites11** [comment]
e2e and 19.3.0 -> 19.3.1 tests are green
missing 19.2.0 -> 19.3.1

**Comment by whites11** [comment]
@T-Kukawka ok to merge when you want

**Review by T-Kukawka — APPROVED** [review]

**Pull request merged**
