### PR TITLE
KVM workload cluster release v14.1.2

### PR DESCRIPTION
**Pull request by tfussell**
Towards https://github.com/giantswarm/giantswarm/issues/18099

We are only changing the OS version to mitigate a kernel issue.

### CODE REVIEW

**Comment by tfussell** [comment]
Automated tests failed due to an unrelated issue. I have tested cluster creation and upgrade from 14.0.0 successfully on `gorgoth`.

**Review by glitchcrab — APPROVED** [review]
letsgooooo

**Review by cornelius-keller — APPROVED** [review]
looks good to me, thanks @tfussell

**Pull request merged**
