### PR TITLE
CAPA: Release v29.2.0.

### PR DESCRIPTION
**Pull request by Gacko**
### Checklist

- [x] Roadmap issue created
- [x] Release uses latest stable Flatcar
- [x] Release uses latest Kubernetes patch version

### Triggering E2E tests

To trigger the E2E test for each new Release added in this PR, add a comment with the following:

`/run releases-test-suites`

If you want to trigger conformance tests, you can do so by adding a comment similar to the following:

`/run conformance-tests PROVIDER=capa RELEASE_VERSION=29.1.0`

For more details see the [README.md](/README.md#running-tests-against-prs).

### CODE REVIEW

**Review by stone-z — APPROVED** [review]

**Comment by Gacko** [comment]
Tests are currently failing because of Teleport Kube Agent. @ssyno is already working on fixing it. We therefore crafted [this draft PR](https://github.com/giantswarm/releases/pull/1420) for testing changes. Once the app got fixed and released, we will integrate the new version in this PR here.

**Review by ssyno — APPROVED** [review]

**Review by ssyno — APPROVED** [review]

**Comment by Gacko** [comment]
Conformance Tests are more or less intended to fail. So no worries!

**Pull request merged**
