### PR TITLE
add aws release 19.2.0

### PR DESCRIPTION
**Pull request by whites11**
### New cluster creation

- [x] IPAM normal mode europe
- [x] IPAM ENI mode europe
- [x] IPAM normal mode china

### Upgrades
- [x] from 18.4.2, IPAM normal mode europe
- [x] from 18.4.2, IPAM ENI mode europe
- [x] from 18.4.2, IPAM normal mode china
- [x] from 19.1.1, IPAM normal mode europe
- [x] from 19.1.1, IPAM ENI mode europe
- [x] from 19.1.1, IPAM normal mode china

### CNCF
- [x] IPAM normal mode europe
- [x] IPAM ENI mode europe

### CODE REVIEW

**Review by calvix — APPROVED** [review]

**Comment by whites11** [comment]
cncf tests failing

**Comment by whites11** [comment]
China tests fail

```
=== NAME  Test_NetworkPolicy
    networkpolicy_test.go:95: timeout waiting for pod np-success to terminate successfully: expected exit code to be 0, got 28
```

not the first time I see this, I believe this is a problem of the test itself. Will check it out tomorrow

**Comment by whites11** [comment]
in ENI mode there is one CNCF test failing:

```
[sig-network] Services should have session affinity work for NodePort service [LinuxOnly] [Conformance]
```

**Comment by whites11** [comment]
@T-Kukawka all tests passed, we have green light to release 19.2.0

**Pull request merged**
