### PR TITLE
CAPZ: Release v27.0.0.

### PR DESCRIPTION
**Pull request by Gacko**
### Checklist

- [x] Roadmap issue created
- [x] Release uses latest stable Flatcar
- [x] Release uses latest Kubernetes patch version

### Triggering E2E tests

To trigger the E2E test for each new Release added in this PR, add a comment with the following:

`/run releases-test-suites`

If you want to trigger conformance tests, you can do so by adding a comment similar to the following:

`/run conformance-tests PROVIDER=azure RELEASE_VERSION=v27.0.0`

For more details see the [README.md](/README.md#running-tests-against-prs).

### CODE REVIEW

**Comment by Gacko** [comment]
/run conformance-tests PROVIDER=azure RELEASE_VERSION=v27.0.0

**Review by weseven — APPROVED** [review]

**Comment by weseven** [comment]
LGTM!

**Pull request merged**
