### PR TITLE
Define and activate release v17.4.2 for AWS.

### PR DESCRIPTION
**Pull request by Gacko**

### CODE REVIEW

**Comment by Gacko** [comment]
`app-operator` v6.3.0 was requested for `> 17.4.1` but it brings a functional change instead of a patch. Maybe we should postpone `app-operator` v6.3.0 to `>= 17.5.0`.

**Comment by Gacko** [comment]
https://github.com/giantswarm/releases/pull/1012/commits/fa0bce99f034e6a4082e2f275f142b66d1c1c9a4 comes from https://github.com/giantswarm/releases/pull/1011. This must be merged first.

**Comment by whites11** [comment]
> `app-operator` v6.3.0 was requested for `> 17.4.1` but it brings a functional change instead of a patch. Maybe we should postpone `app-operator` v6.3.0 to `>= 17.5.0`.

yes please let's leave app operator out of this release and change the requests file

**Comment by Gacko** [comment]
kk, PR inc. :)

**Comment by Gacko** [comment]
I won't touch requests for `cluster-operator` and `chart-operator` since they are already fulfilled in `v17.4.1`.

**Comment by Gacko** [comment]
Here we go: https://github.com/giantswarm/releases/pull/1013

**Comment by whites11** [comment]
Please fix the componentVersion issue I pointed out.
Afterwards we (Phoenix) will take over the release for testing.
Thanks for your contribution @Gacko

**Comment by Gacko** [comment]
Ah, yeah. Sorry. Just read the manual regarding `devctl release create`. The example in the docs doesn't mention this.

**Comment by whites11** [comment]
e2e tests green

**Review by T-Kukawka — APPROVED** [review]

**Pull request merged**
