### PR TITLE
 AWS (CAPA) v28.0.0

### PR DESCRIPTION
**Pull request by weseven**
## Diff from aws-27.0.0

**App diffs**

| app \ release | v27.0.0 | v28.0.0 | change |
| --- | --- | --- | --- |
| cloud-provider-aws | 1.27.7-gs1|1.28.6-gs1 | **minor** |
| cluster-autoscaler | 1.27.3-gs9 |1.28.5-gs1 | **minor** |

**Component diffs**

| component \ release | v27.0.0 | v28.0.0 | change |
| --- | --- | --- | --- |
| kubernetes | 1.27.14 | 1.28.11 |**minor** |

### CODE REVIEW

**Comment by AverageMarcus** [comment]
Testing the Conformance pipeline...

/run conformance-tests RELEASE_VERSION=v28.0.0 PROVIDER=capa

**Comment by weseven** [comment]
Testing upgrade now that capa v27 has been released

/run releases-test-suites

**Review by Gacko — APPROVED** [review]

**Comment by Gacko** [comment]
Conformance tests are failing for Cilium and Ephemeral Containers. Both are known issues and safe to ignore.

**Pull request merged**
