### PR TITLE
Add AWS (CAPA) v26.0.0 release

### PR DESCRIPTION
**Pull request by nprokopic**
Closes https://github.com/giantswarm/roadmap/issues/3531

This PR adds v26.0.0 release.

There are only 3 changes, compared to v25.0.0:
- Kubernetes version
- aws-cloud-controller (a.k.a. cloud-provider-aws)
- cluster-autoscaler 

## Diff

**App diffs**

| app \ release | 25.0.0 | 26.0.0 | change |
| --- | --- | --- | --- |
| cloud-provider-aws | 1.25.14-gs3 | 1.26.11-gs1 | **minor** |
| cluster-autoscaler | 1.27.3-gs9 | 1.27.3-gs10 | **patch** |

**Component diffs**

| component \ release | v25.0.0 | 26.0.0-alpha.2  | change |
| --- | --- | --- | --- |
| kubernetes | 1.25.16 | 1.26.15 | **minor** |

### CODE REVIEW

**Comment by nprokopic** [comment]
Kyverno is sometimes slow to install, or it just gets stuck in pending-install.

```
kubectl get app -n org-nikola
NAME                                       INSTALLED VERSION                                 CREATED AT   LAST DEPLOYED   STATUS
nik26test02                                1.0.0                                             37m          37m             deployed
nik26test02-app-operator                   6.11.0-ca3ccbc05cf9111a22904bcf2b521921fddaaaa8   37m          37m             deployed
nik26test02-aws-ebs-csi-driver-smons       0.1.0                                             37m          21m             deployed
nik26test02-aws-pod-identity-webhook       1.16.0                                            37m          21m             deployed
nik26test02-capi-node-labeler              0.5.0                                             37m          29m             deployed
nik26test02-cert-exporter                  2.9.0                                             37m          2m16s           deployed
nik26test02-cert-manager                   3.7.7                                             37m          25m             deployed
nik26test02-chart-operator                 3.2.1                                             37m          29m             deployed
nik26test02-chart-operator-extensions      1.1.2                                             37m          25m             deployed
nik26test02-cilium-servicemonitors         0.1.2                                             37m          27m             deployed
nik26test02-cluster-autoscaler             1.27.3-gs9                                        37m          2m9s            deployed
nik26test02-etcd-k8s-res-count-exporter    1.10.0                                            37m          2m26s           deployed
nik26test02-external-dns                   3.1.0                                             37m          26m             deployed
nik26test02-grafana-agent                  0.4.3                                             27m          26m             deployed
nik26test02-irsa-servicemonitors           0.0.1                                             37m          21m             deployed
nik26test02-k8s-audit-metrics                                                                37m
nik26test02-k8s-dns-node-cache                                                               37m
nik26test02-kube-prometheus-stack          9.1.2                                             27m          26m             deployed
nik26test02-kyverno                        0.17.13                                           26m          25m             pending-install
nik26test02-kyverno-policies                                                                 26m
nik26test02-kyverno-policy-operator                                                          26m
nik26test02-metrics-server                                                                   37m
nik26test02-net-exporter                   1.19.0                                            37m          26m             deployed
nik26test02-node-exporter                                                                    37m
nik26test02-observability-bundle           1.3.4                                             37m          27m             deployed
nik26test02-prometheus-agent               0.6.9                                             27m          26m             deployed
nik26test02-prometheus-blackbox-exporter   0.4.1                                             37m          26m             deployed
nik26test02-prometheus-operator-crd        9.0.0                                             27m          27m             deployed
nik26test02-promtail                       1.5.3                                             27m          26m             deployed
nik26test02-security-bundle                1.7.0                                             37m          26m             deployed
nik26test02-teleport-kube-agent            0.9.0                                             37m          29m             deployed
nik26test02-vertical-pod-autoscaler        5.2.2                                             37m          26m             deployed
```

**Comment by nprokopic** [comment]
change in app state for v26 test

```
kubectl get app -n org-nikola
NAME                                       INSTALLED VERSION                                 CREATED AT   LAST DEPLOYED   STATUS
nik26test02                                1.0.0                                             45m          45m             deployed
nik26test02-app-operator                   6.11.0-ca3ccbc05cf9111a22904bcf2b521921fddaaaa8   44m          44m             deployed
nik26test02-aws-ebs-csi-driver-smons       0.1.0                                             44m          29m             deployed
nik26test02-aws-pod-identity-webhook       1.16.0                                            44m          29m             deployed
nik26test02-capi-node-labeler              0.5.0                                             44m          37m             deployed
nik26test02-cert-exporter                  2.9.0                                             44m          9m45s           deployed
nik26test02-cert-manager                   3.7.7                                             44m          33m             deployed
nik26test02-chart-operator                 3.2.1                                             44m          37m             deployed
nik26test02-chart-operator-extensions      1.1.2                                             44m          33m             deployed
nik26test02-cilium-servicemonitors         0.1.2                                             44m          34m             deployed
nik26test02-cluster-autoscaler             1.27.3-gs9                                        44m          9m38s           deployed
nik26test02-etcd-k8s-res-count-exporter    1.10.0                                            44m          9m55s           deployed
nik26test02-external-dns                   3.1.0                                             44m          33m             deployed
nik26test02-grafana-agent                  0.4.3                                             34m          33m             deployed
nik26test02-irsa-servicemonitors           0.0.1                                             44m          29m             deployed
nik26test02-k8s-audit-metrics              0.9.0                                             44m          5m32s           deployed
nik26test02-k8s-dns-node-cache                                                               44m                          invalid-manifest
nik26test02-kube-prometheus-stack          9.1.2                                             34m          33m             deployed
nik26test02-kyverno                        0.17.13                                           34m          33m             pending-install
nik26test02-kyverno-policies                                                                 34m                          invalid-manifest
nik26test02-kyverno-policy-operator                                                          34m
nik26test02-metrics-server                 2.4.2                                             44m          5m42s           deployed
nik26test02-net-exporter                   1.19.0                                            44m          34m             deployed
nik26test02-node-exporter                  1.19.0                                            44m          5m47s           deployed
nik26test02-observability-bundle           1.3.4                                             44m          34m             deployed
nik26test02-prometheus-agent               0.6.9                                             34m          34m             deployed
nik26test02-prometheus-blackbox-exporter   0.4.1                                             44m          33m             deployed
nik26test02-prometheus-operator-crd        9.0.0                                             34m          34m             deployed
nik26test02-promtail                       1.5.3                                             34m          33m             deployed
nik26test02-security-bundle                1.7.0                                             44m          34m             deployed
nik26test02-teleport-kube-agent            0.9.0                                             44m          37m             deployed
nik26test02-vertical-pod-autoscaler        5.2.2                                             44m          34m             deployed
```

**Review by Gacko — APPROVED** [review]

**Comment by nprokopic** [comment]
CAPA Standard failed with this:

```
  {"level":"info","ts":"2024-07-04T15:55:10Z","msg":"Found Cluster org-t-haptktws6vv9k4754e/t-pr386931o1h93lctj1 condition Ready with Status='False' and Reason='NatGatewaysCreationStarted', expected condition with Status='True' and Reason=''"}
  {"level":"info","ts":"2024-07-04T15:55:20Z","msg":"Found Cluster org-t-haptktws6vv9k4754e/t-pr386931o1h93lctj1 condition Ready with Status='False' and Reason='NatGatewaysCreationStarted', expected condition with Status='True' and Reason=''"}
  [FAILED] in [It] - /app/internal/common/basic.go:119 @ 07/04/24 15:55:26.25
• [FAILED] [900.001 seconds]
Common tests basic [It] has Cluster Ready condition with Status='True'
/app/internal/common/basic.go:113

  [FAILED] Timed out after 900.000s.
  Expected
      <bool>: false
  to be true
  In [It] at: /app/internal/common/basic.go:119 @ 07/04/24 15:55:26.25
```

and this 

```
Common tests hello world cluster wildcard ingress DNS must be resolvable
/app/internal/common/hello.go:93
  [FAILED] in [It] - /app/internal/common/hello.go:121 @ 07/04/24 16:06:12.749
• [FAILED] [600.001 seconds]
Common tests hello world [It] cluster wildcard ingress DNS must be resolvable
/app/internal/common/hello.go:93

  [FAILED] Timed out after 600.001s.
  The function passed to Eventually returned the following error:
      <*net.DNSError | 0xc0006dc2c0>: 
      lookup [hello-world.t-pr386931o1h93lctj1.gaws.gigantic.io](http://hello-world.t-pr386931o1h93lctj1.gaws.gigantic.io/) on 172.31.0.10:53: server misbehaving
      {
          Err: "server misbehaving",
          Name: "[hello-world.t-pr386931o1h93lctj1.gaws.gigantic.io](http://hello-world.t-pr386931o1h93lctj1.gaws.gigantic.io/)",
          Server: "172.31.0.10:53",
          IsTimeout: false,
          IsTemporary: true,
          IsNotFound: false,
      }
  In [It] at: /app/internal/common/hello.go:121 @ 07/04/24 16:06:12.749
```

Didn't see this issue before.

I have to update the PR anyway so will re-run the tests.

**Comment by nprokopic** [comment]
Standard suite failing again with this same issue

```
Common tests hello world cluster wildcard ingress DNS must be resolvable
/app/internal/common/hello.go:91
  [FAILED] in [It] - /app/internal/common/hello.go:110 @ 07/05/24 11:29:21.515
• [FAILED] [600.003 seconds]
Common tests hello world [It] cluster wildcard ingress DNS must be resolvable
/app/internal/common/hello.go:91

  [FAILED] Timed out after 600.002s.
  The function passed to Eventually returned the following error:
      <*net.DNSError | 0xc000c000c0>: 
      lookup [hello-world.t-y51alziyvfyu2qf900.gaws.gigantic.io](http://hello-world.t-y51alziyvfyu2qf900.gaws.gigantic.io/) on 172.31.0.10:53: server misbehaving
      {
          Err: "server misbehaving",
          Name: "[hello-world.t-y51alziyvfyu2qf900.gaws.gigantic.io](http://hello-world.t-y51alziyvfyu2qf900.gaws.gigantic.io/)",
          Server: "172.31.0.10:53",
          IsTimeout: false,
          IsTemporary: true,
          IsNotFound: false,
      }
  In [It] at: /app/internal/common/hello.go:110 @ 07/05/24 11:29:21.515
```

The other issue with NAT gateways creation didn't happen this time.

**Comment by nprokopic** [comment]
This time same issue in CAPA upgrade suite

```
Basic upgrade test hello world cluster wildcard ingress DNS must be resolvable
/app/internal/common/hello.go:91
  [FAILED] in [It] - /app/internal/common/hello.go:110 @ 07/05/24 11:44:33.773
• [FAILED] [600.001 seconds]
Basic upgrade test hello world [It] cluster wildcard ingress DNS must be resolvable
/app/internal/common/hello.go:91

  [FAILED] Timed out after 600.001s.
  The function passed to Eventually returned the following error:
      <*net.DNSError | 0xc000b9a380>: 
      lookup [hello-world.t-xavb3cocbnmbbe7ivr.gaws.gigantic.io](http://hello-world.t-xavb3cocbnmbbe7ivr.gaws.gigantic.io/) on 172.31.0.10:53: server misbehaving
      {
          Err: "server misbehaving",
          Name: "[hello-world.t-xavb3cocbnmbbe7ivr.gaws.gigantic.io](http://hello-world.t-xavb3cocbnmbbe7ivr.gaws.gigantic.io/)",
          Server: "172.31.0.10:53",
          IsTimeout: false,
          IsTemporary: true,
          IsNotFound: false,
      }
  In [It] at: /app/internal/common/hello.go:110 @ 07/05/24 11:44:33.773
```

**Comment by AverageMarcus** [comment]
Just checking that an update to pr-gatekeeper to check for releases tests has worked...

/recheck

**Comment by weseven** [comment]
capa-iam-operator is at 0.26.0 on grizzly, re-testing :crossed_fingers: 


/run releases-test-suites

**Comment by weseven** [comment]
upgrade went well, standard failed because of apps taking too long (I think kyverno was stuck :disappointed:).
It seems like a fluke, retrying :four_leaf_clover:  

/run releases-test-suites

**Pull request merged**
