### PR TITLE
add azure release 18.0.2

### PR DESCRIPTION
**Pull request by whites11**
wip release for internal use only

### CODE REVIEW

**Review by Gacko — APPROVED** [review]

**Comment by Gacko** [comment]
@whites11 @T-Kukawka Mind giving additional approval? I tested it with several clusters yesterday and it's a huge improvement even though I still spotted a single cluster not coming up. Calico CRD installer runs at the very beginning and even other resources like charts come up much faster now.

**Comment by T-Kukawka** [comment]
Yes, first i want to create release issue etc

**Comment by Gacko** [comment]
I basically don't care, that's up to you guys to decide.

Customers have no advantage on existing clusters and on new clusters it is not a show stopper - just annoying when it takes several attempts until the cluster is up.

I would do it just to have a consistent state on all installations and no "temporary" releases on test installations.

**Comment by T-Kukawka** [comment]
We have decided not to release this part for customers. Release is available internally. There is little advantage of upgrading to that release especially  that the nodes will be rolled for 'no reason' in existing clusters. We suspect no new cluster from customers coming up any time soon. Closing.

**Pull request closed without merging**
