### PR TITLE
CAPI: Request `cert-exporter` v2.9.2.

### PR DESCRIPTION
**Pull request by T-Kukawka**
Towards: https://gigantic.slack.com/archives/C6L8J93N0/p1729068032911919

### Checklist

- [ ] Roadmap issue created
- [ ] Release uses latest stable Flatcar
- [ ] Release uses latest Kubernetes patch version

### Triggering E2E tests

To trigger the E2E test for each new Release added in this PR, add a comment with the following:

`/run releases-test-suites`

If you want to trigger conformance tests, you can do so by adding a comment similar to the following:

`/run conformance-tests PROVIDER=capa RELEASE_VERSION=29.1.0`

For more details see the [README.md](/README.md#running-tests-against-prs).

### CODE REVIEW

**Comment by Gacko** [comment]
Can you also update it for CAPZ and other relevant providers? I remember this to be important because of VPA, right?

**Comment by Gacko** [comment]
Also this makes CI fail because your request would expect existing releases to already have that version.

Is this really important for old releases or would it also be enough for customers to just update to a v29.x.x as soon as possible?

**Comment by T-Kukawka** [comment]
@Gacko this is relevant for one of the customers as they are already facing the issue in v25 series, and they are keeping all their environments in sync, hence i would say with next release iteration it will be very beneficial to everyone to add it

**Comment by T-Kukawka** [comment]
@Gacko i have added it also for vsphere, azure already has this requirement for latest and we are working with customers to update. Their workloads are not that intensive hence noone is facing this issue besides ones in CAPA v25.

**Review by Gacko — APPROVED** [review]

**Pull request merged**
