### PR TITLE
CAPVCD: Release v29.0.0.

### PR DESCRIPTION
**Pull request by njuettner**
⚠️ WIP 

**Waiting for: https://github.com/giantswarm/releases/pull/1490**

Towards: https://github.com/giantswarm/roadmap/issues/3712

### Checklist

- [x] Roadmap issue created
- [x] Release uses latest stable Flatcar
- [x] Release uses latest Kubernetes patch version

### Triggering E2E tests

To trigger the E2E test for each new Release added in this PR, add a comment with the following:

`/run releases-test-suites`

If you want to trigger conformance tests, you can do so by adding a comment similar to the following:

`/run conformance-tests PROVIDER=capa RELEASE_VERSION=29.1.0`

For more details see the [README.md](/README.md#running-tests-against-prs).

### CODE REVIEW

**Comment by njuettner** [comment]
/run releases-test-suites TARGET_SUITES=./providers/capvcd/standard TARGET_RELEASES=cloud-director-29.0.0

**Comment by Gacko** [comment]
First try - nice! Lemme get my notebook to review this for you. 🙂

**Review by Gacko — APPROVED** [review]
LGTM! (I know we shouldn't merge this, yet, as it would end up in the v28.0.0 branch)

**Comment by Gacko** [comment]
/run releases-test-suites TARGET_SUITES=./providers/capvcd/standard PREVIOUS_RELEASE=28.0.0 TARGET_RELEASES=cloud-director-29.0.0

**Comment by Gacko** [comment]
/run releases-test-suites TARGET_SUITES=./providers/capvcd/upgrade PREVIOUS_RELEASE=28.0.0 TARGET_RELEASES=cloud-director-29.0.0

**Comment by Gacko** [comment]
/run releases-test-suites PREVIOUS_RELEASE=28.0.0 TARGET_RELEASES=cloud-director-29.0.0

**Comment by Gacko** [comment]
/run releases-test-suites PREVIOUS_RELEASE=28.0.0 TARGET_RELEASES=cloud-director-29.0.0

**Review by vxav — APPROVED** [review]

**Pull request merged**
