### PR TITLE
AWS v18.4.0

### PR DESCRIPTION
**Pull request by njuettner**
Issue: https://github.com/giantswarm/roadmap/issues/2367

### Checklist
- [x] Roadmap issue created
- [x] Release uses latest stable Flatcar
- [x] Release uses latest Kubernetes patch version

### CODE REVIEW

**Review by T-Kukawka — APPROVED** [review]

**Comment by T-Kukawka** [comment]
changed announcements slightly, please check

**Comment by njuettner** [comment]
Makes sense to me 👍🏻

**Pull request merged**
