### PR TITLE
Only push releases for changed providers

### PR DESCRIPTION
**Pull request by tfussell**
For https://github.com/giantswarm/giantswarm/issues/16770

### CODE REVIEW

**Comment by tfussell** [comment]
Tested changing one provider and all three providers. You can see the logs here https://app.circleci.com/pipelines/github/giantswarm/releases?branch=dynamic-config.

There are two possible issues:
- We can't use `requires` between separate workflows so PRs that change all 3 providers such as adding requests can potentially interfere during on parallel `git pull` and `git push`.
- We can't require status checks to pass because we don't know which one will run.

I think this is still an overall improvement for reducing build time and adding fewer unused charts to the `releases-test-catalog`.

**Review by MarcelMue — APPROVED** [review]
That's neat!

**Comment by fiunchinho** [comment]
This is great! Thanks Thomas

**Comment by tfussell** [comment]
I'm afraid this broke the rendered helm charts even though I was sure I tested it. I will retry later today or tomorrow and get someone else to verify with me.

**Pull request merged**
