### PR TITLE
patch external-dns in aws v19

### PR DESCRIPTION
**Pull request by mcharriere**
Coming from this [thread](https://gigantic.slack.com/archives/C02EVLE9W/p1686814697921809?thread_ts=1686751793.540999&cid=C02EVLE9W). This PR patches the v19 release to include a hotfix of external-dns-app that blocks China installations upgrade to v19.

### Checklist
- [ ] Roadmap issue created
- [ ] Release uses latest stable Flatcar
- [ ] Release uses latest Kubernetes patch version

### CODE REVIEW

**Review by calvix — APPROVED** [review]

**Comment by T-Kukawka** [comment]
@mcharriere this was tested on 18 and 19 and the upgrade right?

**Comment by mcharriere** [comment]
Yes, tested on gaia creating a new cluster and upgrading from 18.4.2.

I wanted to test it on giraffe (because that's where the bug is) but it's not working atm.

**Comment by T-Kukawka** [comment]
okay @mcharriere, when giraffe is available and you finish your last test, u can merge it 👊

**Comment by mcharriere** [comment]
tested on giraffe too. works well! thank you

**Pull request merged**
