### PR TITLE
AWS workload cluster release 14.0.0 with Kubernetes 1.19

### PR DESCRIPTION
**Pull request by MarcelMue**
Includes k8s 1.19.4 - tested against CNCF.

### CODE REVIEW

**Comment by calvix** [comment]
cncf certified provider PR https://github.com/cncf/k8s-conformance/pull/1302

**Comment by calvix** [comment]
CNCF pr for certification merged, everything tested, this is done from my part

**Comment by MarcelMue** [comment]
> CNCF pr for certification merged, everything tested, this is done from my part

Music to my ears!

**Comment by calvix** [comment]
ready to be merged from my side

**Review by njuettner — APPROVED** [review]

**Review by anvddriesch — APPROVED** [review]

**Pull request merged**
