### PR TITLE
Azure v20 beta1

### PR DESCRIPTION
**Pull request by whites11**
### Checklist
- [ ] Roadmap issue created
- [ ] Release uses latest stable Flatcar
- [ ] Release uses latest Kubernetes patch version

### CODE REVIEW

**Comment by whites11** [comment]
CNCF tests green

**Review by T-Kukawka — APPROVED** [review]

**Comment by whites11** [comment]
it is impossible to run e2e tests because infrastructure is not working.
we made some manual testing and decided to release tomorrow morning.
no announcements to the customers will be made.
internal announcement will be made

**Pull request merged**
