### PR TITLE
Define and activate release v12.7.1 for AWS

### PR DESCRIPTION
**Pull request by alex-dabija**
AWS release v12.7.1 ...

### CODE REVIEW

**Comment by njuettner** [comment]
Tested it manually in gauss and giraffe everthing worked. 

I really don't know why it failed, no logs and no information 😞 .

```json
{
"kind": "Status",
"apiVersion": "v1",
"metadata": {},
"status": "Failure",
"message": "pods \"a577c10f-490a-11eb-8cbb-ca9518d9e43b-test-aws-xmq6z-pod-hs9c9\" not found",
"reason": "NotFound",
"details": {
"name": "a577c10f-490a-11eb-8cbb-ca9518d9e43b-test-aws-xmq6z-pod-hs9c9",
"kind": "pods"
},
"code": 404
}
```

**Comment by njuettner** [comment]
ok looks good now, awscnfm tests were flaky.

**Review by xh3b4sd — APPROVED** [review]

**Review by cornelius-keller — APPROVED** [review]

**Pull request merged**
