### PR TITLE
Archive AWS release v9.0.4

### PR DESCRIPTION
**Pull request by alex-dabija**
It's unused and obsolete.

### CODE REVIEW

**Comment by xh3b4sd** [comment]
Just FMI how did you figure out it is unused? At some point we could not take Cortex for granted. Not sure if this source of truth is actually reflecting reality now.

**Comment by calvix** [comment]
yeah dashboard in  grafana is definitely good source of truth :p got burned few times

**Comment by alex-dabija** [comment]
I used @marians po-utils script from [po-utils](https://github.com/giantswarm/po-utils).

**Comment by alex-dabija** [comment]
I also checked the following graph: https://giantswarm.grafana.net/d/6Jt4OwqZk/clusters?viewPanel=39&orgId=1 .

**Review by xh3b4sd — APPROVED** [review]

**Review by calvix — APPROVED** [review]

**Pull request merged**
