### PR TITLE
Add CAPA v25.2.0

### PR DESCRIPTION
**Pull request by nprokopic**
Towards https://github.com/giantswarm/roadmap/issues/3610

This release updates cluster-aws Helm chart, which brings improvements for container registry usage.

#### Changed

- All workload clusters will by default use Zot registry as a pull-through cache of Azure Container Registry.

### Checklist
- [x] Roadmap issue created
- [x] Release uses latest stable Flatcar
- [x] Release uses latest Kubernetes 1.25.x patch version

### Triggering e2e tests

To trigger the E2E test for each new Release added in this PR add a comment with the following:

`/run releases-test-suites`

If you want to trigger conformance tests you can do so by adding a comment similar to the following:

`/run conformance-tests RELEASE_VERSION=v28.0.0 PROVIDER=capa`

For more details see the [README.md](/README.md#running-tests-against-prs)

### CODE REVIEW

**Comment by nprokopic** [comment]
/run releases-test-suites TARGET_SUITES=./providers/capa/standard

**Comment by nprokopic** [comment]
/run releases-test-suites TARGET_SUITES=./providers/capa/upgrade PREVIOUS_RELEASE=aws-v25.0.0

**Comment by nprokopic** [comment]
/run releases-test-suites TARGET_SUITES=./providers/capa/upgrade PREVIOUS_RELEASE=25.0.0

**Comment by nprokopic** [comment]
All upgrade tests have passed, it's the AfterSuite clean-up that failed

```
{"level":"info","ts":"2024-07-30T11:56:22Z","msg":"Checking if Cluster 't-tjupwewq9lhluvusov' still exists"}
  {"level":"info","ts":"2024-07-30T11:56:22Z","msg":"Still exists: Cluster 't-tjupwewq9lhluvusov' (finalizers: [cluster.cluster.x-k8s.io](http://cluster.cluster.x-k8s.io/))"}
  {"level":"info","ts":"2024-07-30T11:56:32Z","msg":"Checking if Cluster 't-tjupwewq9lhluvusov' still exists"}
  {"level":"info","ts":"2024-07-30T11:56:32Z","msg":"Still exists: Cluster 't-tjupwewq9lhluvusov' (finalizers: [cluster.cluster.x-k8s.io](http://cluster.cluster.x-k8s.io/))"}
  [FAILED] in [AfterSuite] - /app/internal/suite/setup.go:56 @ 07/30/24 11:56:42.456
[AfterSuite] [FAILED] [1808.051 seconds]
[AfterSuite] 
/app/internal/suite/setup.go:46

  [FAILED] Expected success, but got an error:
      <context.deadlineExceededError>: 
      context deadline exceeded
      {}
  In [AfterSuite] at: /app/internal/suite/setup.go:56 @ 07/30/24 11:56:42.456
```

**Comment by nprokopic** [comment]
Testing minor upgrade 25.1.0 to 25.2.0

/run releases-test-suites TARGET_SUITES=./providers/capa/upgrade PREVIOUS_RELEASE=25.1.0

**Comment by nprokopic** [comment]
Both standard and upgrade e2e tests suites have passed successfully :heavy_check_mark: :tada: 

@giantswarm/sig-product please check the v25.2.0 announcement and README.

**Review by T-Kukawka — APPROVED** [review]

**Comment by nprokopic** [comment]
Thanks Tobi!

**Pull request merged**
