### PR TITLE
Add kvm 13.2.0 release

### PR DESCRIPTION
**Pull request by tomahawk28**

### CODE REVIEW

**Comment by tomahawk28** [comment]
@giantswarm/team-rocket I'm getting following errors from kvm-operator v3.15.0
```
D 03/31 14:58:56 /apis/provider.giantswarm.io/v1alpha1/namespaces/default/kvmconfigs/m8xf9 configmap.GetDesiredState computing the new config maps | kvm-operator/service/controller/resource/configmap/desired.go:26 | controller=kvm-operator | event=update | loop=3 | version=330005743
E 03/31 14:59:01 /apis/provider.giantswarm.io/v1alpha1/namespaces/default/kvmconfigs/m8xf9 configmap.GetDesiredState retrying due to error | operatorkit/v4/pkg/resource/wrapper/retryresource/crud_resource.go:89 | controller=kvm-operator | event=update | loop=3 | version=330005743
        /go/pkg/mod/github.com/giantswarm/operatorkit/v4@v4.2.0/pkg/resource/wrapper/retryresource/crud_resource.go:82
        /root/project/service/controller/resource/configmap/desired.go:30
        /root/project/service/controller/resource/configmap/desired.go:82
        /root/project/service/controller/cloudconfig/master_template.go:22
        /root/project/service/controller/cloudconfig/functions.go:49
        /root/project/service/controller/cloudconfig/functions.go:36
        /go/pkg/mod/github.com/giantswarm/certs/v3@v3.1.1/pkg/certs/searcher.go:230
        /go/pkg/mod/github.com/giantswarm/certs/v3@v3.1.1/pkg/certs/searcher.go:277
        timeout error: waiting secrets, selector = "giantswarm.io/certificate=service-account, giantswarm.io/cluster=m8xf9"
D 03/31 14:59:02 /apis/provider.giantswarm.io/v1alpha1/namespaces/default/kvmconfigs/m8xf9 configmap.GetDesiredState computing the new config maps | kvm-operator/service/controller/resource/configmap/desired.go:26 | controller=kvm-operator | event=update | loop=3 | version=330005743
E 03/31 14:59:05 /apis/provider.giantswarm.io/v1alpha1/namespaces/default/kvmconfigs/m8xf9 configmap.GetDesiredState retrying due to error | operatorkit/v4/pkg/resource/wrapper/retryresource/crud_resource.go:89 | controller=kvm-operator | event=update | loop=3 | version=330005743
        /go/pkg/mod/github.com/giantswarm/operatorkit/v4@v4.2.0/pkg/resource/wrapper/retryresource/crud_resource.go:82
        /root/project/service/controller/resource/configmap/desired.go:30
        /root/project/service/controller/resource/configmap/desired.go:82
        /root/project/service/controller/cloudconfig/master_template.go:74
        /go/pkg/mod/github.com/giantswarm/k8scloudconfig/v10@v10.1.0/pkg/template/cloudconfig.go:35
        invalid config error: template.CloudConfigConfig.validation error: component `Kubernetes` requires version following constraint `>= 1.19.0`, got `v1.18.12`
```
Can you have a look manybe?

**Comment by tomahawk28** [comment]
If we only expect compatibility from k8s v1.19.0, why exactly kvm-operator should reject older version?
changelog from kvm-operator is here; https://github.com/giantswarm/kvm-operator/blob/master/CHANGELOG.md#3150---2021-03-29

**Comment by tfussell** [comment]
> If we only expect compatibility from k8s v1.19.0, why exactly kvm-operator should reject older version?
> changelog from kvm-operator is here; https://github.com/giantswarm/kvm-operator/blob/master/CHANGELOG.md#3150---2021-03-29

There was a breaking change in `k8scloudconfig` v10 needed to support k8s 1.19 and kvm-operator master uses k8scc v10. To be specific, the upstream images changed and the scheduler config changed in backwards-incompatible ways.

**Comment by tfussell** [comment]
@tomahawk28 For the first error, it looks like certs are missing. I believe they are managed by cluster-operator so make sure it's running and that there are no errors in the logs.

For the second error, you should use k8s 1.19 in the Release CR.

**Comment by tomahawk28** [comment]
Thanks, I bumped up kubernetse version to 1.19.4.

**Comment by tomahawk28** [comment]
There was a nil-pointer error at some point. 
```
D 04/01 08:11:08 /apis/provider.giantswarm.io/v1alpha1/namespaces/default/kvmconfigs/vz6x3 nodecontroller booting new controller | kvm-operator/service/controller/resource/nodecontroller/create.go:91 | controller=kvm-operator | event=update | loop=1 | version=330262867
E0401 08:11:08.069444       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1417 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x181e4e0, 0x28130d0)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/runtime/runtime.go:48 +0x86
panic(0x181e4e0, 0x28130d0)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/giantswarm/k8sclient/v5/pkg/k8sclient.(*Clients).RESTConfig(0x0, 0xc00104dc10)
        /go/pkg/mod/github.com/giantswarm/k8sclient/v5@v5.11.0/pkg/k8sclient/clients.go:217 +0x22
github.com/giantswarm/kvm-operator/service/controller/internal/nodecontroller.(*Controller).Boot(0xc000670000, 0x1cc3b18, 0xc000a658f0)
        /root/project/service/controller/internal/nodecontroller/controller.go:113 +0xd0
github.com/giantswarm/kvm-operator/service/controller/resource/nodecontroller.(*Resource).EnsureCreated(0xc00073cdc0, 0x1cc3b18, 0xc000a658f0, 0x19e91e0, 0xc00088bb00, 0x0, 0x0)
        /root/project/service/controller/resource/nodecontroller/create.go:92 +0x7a5
github.com/giantswarm/operatorkit/v4/pkg/resource/wrapper/retryresource.(*basicResource).EnsureCreated.func1(0xc0006f0260, 0xc000f18e60)
        /go/pkg/mod/github.com/giantswarm/operatorkit/v4@v4.2.0/pkg/resource/wrapper/retryresource/basic_resource.go:50 +0x64
github.com/cenkalti/backoff.RetryNotify(0xc0016d1828, 0x7fb1b1ce4080, 0xc0006f0260, 0xc0016d1808, 0x0, 0x0)
        /go/pkg/mod/github.com/cenkalti/backoff@v2.2.1+incompatible/retry.go:37 +0x1e8
github.com/giantswarm/backoff.RetryNotify(0xc0016d1828, 0x1c99080, 0xc0006f0260, 0xc0016d1808, 0x1c99b00, 0x7fb1b1aca720)
        /go/pkg/mod/github.com/giantswarm/backoff@v0.2.0/retry.go:21 +0x71
github.com/giantswarm/operatorkit/v4/pkg/resource/wrapper/retryresource.(*basicResource).EnsureCreated(0xc0007cc1e0, 0x1cc3b18, 0xc000a658f0, 0x19e91e0, 0xc00088bb00, 0xc0006605a0, 0x0)
        /go/pkg/mod/github.com/giantswarm/operatorkit/v4@v4.2.0/pkg/resource/wrapper/retryresource/basic_resource.go:62 +0x105
github.com/giantswarm/operatorkit/v4/pkg/resource/wrapper/metricsresource.(*basicResource).EnsureCreated(0xc0000b6270, 0x1cc3b18, 0xc000a658f0, 0x19e91e0, 0xc00088bb00, 0x0, 0x0)
        /go/pkg/mod/github.com/giantswarm/operatorkit/v4@v4.2.0/pkg/resource/wrapper/metricsresource/basic_resource.go:41 +0x23d
github.com/giantswarm/operatorkit/v4/pkg/controller.(*Controller).updateFunc(0xc0001bc0e0, 0x1cc3b18, 0xc000a658f0, 0x19e91e0, 0xc00088bb00, 0x0, 0x0)
        /go/pkg/mod/github.com/giantswarm/operatorkit/v4@v4.2.0/pkg/controller/controller.go:547 +0x262
github.com/giantswarm/operatorkit/v4/pkg/controller.(*Controller).reconcile(0xc0001bc0e0, 0x1cc3b18, 0xc000824c00, 0xc00099d5f0, 0x7, 0xc00099d5e0, 0x5, 0x19e91e0, 0xc00088bb00, 0x0, ...)
        /go/pkg/mod/github.com/giantswarm/operatorkit/v4@v4.2.0/pkg/controller/controller.go:512 +0x6e5
github.com/giantswarm/operatorkit/v4/pkg/controller.(*Controller).Reconcile(0xc0001bc0e0, 0xc00099d5f0, 0x7, 0xc00099d5e0, 0x5, 0xc000a7dd88, 0xc0000bde60, 0xc0000bdde8, 0xc0000bddd0)
        /go/pkg/mod/github.com/giantswarm/operatorkit/v4@v4.2.0/pkg/controller/controller.go:310 +0x4e5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0010073b0, 0x18897e0, 0xc000f186a0, 0x0)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/internal/controller/controller.go:244 +0x2a9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0010073b0, 0x203000)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/internal/controller/controller.go:218 +0xb0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(...)
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/internal/controller/controller.go:197
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc0007c3b10)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0007c3b10, 0x1c8fc80, 0xc000f0f920, 0x100000001, 0xc000f00300)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0007c3b10, 0x3b9aca00, 0x0, 0x1, 0xc000f00300)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc0007c3b10, 0x3b9aca00, 0xc000f00300)
        /go/pkg/mod/k8s.io/apimachinery@v0.18.9/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.4/pkg/internal/controller/controller.go:179 +0x3d6
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x15fb302]
```

**Pull request closed without merging**
