### PR TITLE
CAPZ: Deprecate v29.1.0.

### PR DESCRIPTION
**Pull request by T-Kukawka**
### Checklist

- [ ] Roadmap issue created
- [ ] Release uses latest stable Flatcar
- [ ] Release uses latest Kubernetes patch version

### Triggering E2E tests

To trigger the E2E test for each new Release added in this PR, add a comment with the following:

`/run releases-test-suites`

If you want to trigger conformance tests, you can do so by adding a comment similar to the following:

`/run conformance-tests PROVIDER=capa RELEASE_VERSION=29.1.0`

For more details see the [README.md](/README.md#running-tests-against-prs).

### CODE REVIEW

**Comment by Gacko** [comment]
/run releases-test-suites TARGET_SUITES=./providers/capz/upgrade PREVIOUS_RELEASE=28.0.0 TARGET_RELEASES=azure-29.2.0

**Review by Gacko — APPROVED** [review]

**Comment by T-Kukawka** [comment]
@Gacko Vintage releases were simpler with this 😂

**Comment by Gacko** [comment]
The `releases.json` would get updated by CI after merging this PR, so no worries. And the `.diff` is cosmetic.

**Comment by Gacko** [comment]
... and I think I already ran the releases test suites for upgrading from v28.0.0 to v29.2.0 in the CAPZ v29.2.0 Release PR. So theoretically we could skip CI.

On the other hand I kicked it now, so let's wait a few minutes. 🙂

**Pull request merged**
