### PR TITLE
Define and activate KVM 11.2.0 release

### PR DESCRIPTION
**Pull request by sslavic**

### CODE REVIEW

**Comment by sslavic** [comment]
Tested on geckon:
- clean install of 11.2.0 tenant clusters
- upgrading a tenant cluster from 11.1.0 to 11.2.0

**Comment by tfussell** [comment]
I think `11.1.0` should have been deactivated when `11.2.0` was activated. I'll make a PR for that.

**Comment by sslavic** [comment]
@tfussell you're right; I've already included 11.1.0 deactivation in 11.2.1 definition PR https://github.com/giantswarm/releases/pull/139

**Comment by tfussell** [comment]
> @tfussell you're right; I've already included 11.1.0 deactivation in 11.2.1 definition PR #139

Good to hear!

**Comment by sslavic** [comment]
@tfussell feel free to deactivate in separate PR, I'll fix merge conflict in https://github.com/giantswarm/releases/pull/139

**Pull request merged**
