### PR TITLE
Add test release to test upgrade to coredns

### PR DESCRIPTION
**Pull request by ericgraf**

### CODE REVIEW

**Comment by ericgraf** [comment]
in v12.7.0 coredns deploy gets created
```
egraf@ubuntu-focal:~$ k-all get deploy --watch
giantswarm-bg2mt
NAMESPACE     NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
giantswarm    chart-operator            1/1     1            1           8m12s
kube-system   cert-manager-cainjector   1/1     1            1           2m52s
kube-system   cert-manager-controller   1/1     1            1           2m52s
kube-system   cert-manager-webhook      1/1     1            1           2m52s
kube-system   cluster-autoscaler        1/1     1            1           2m28s
kube-system   coredns                   3/3     3            3           2m28s
kube-system   external-dns              1/1     1            1           2m22s
kube-system   kube-state-metrics        1/1     1            1           5m25s
kube-system   metrics-server            1/1     1            1           2m21s

```

but this is not the case in test release v14.0.1-coredns deploy never gets created
```
giantswarm-diir5
NAMESPACE     NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
giantswarm    chart-operator            1/1     1            1           42m
kube-system   cert-manager-cainjector   1/1     1            1           36m
kube-system   cert-manager-controller   1/1     1            1           36m
kube-system   cert-manager-webhook      1/1     1            1           36m
kube-system   cluster-autoscaler        1/1     1            1           34m
kube-system   external-dns              0/1     1            0           34m
kube-system   kube-state-metrics        1/1     1            1           36m
kube-system   metrics-server            1/1     1            1           34m

```

**Comment by tfussell** [comment]
@ericgraf still using this test release?

**Comment by ericgraf** [comment]
> @ericgraf still using this test release?

Yep, I am done with it. 

@MarcelMue you were using this at some point.  Are you done using this test release?

**Comment by MarcelMue** [comment]
Let's get rid of it :)

**Pull request closed without merging**
