### PR TITLE
Upgrade cert-manager-app to 2.24.1 in AWS v19.0.0

### PR DESCRIPTION
**Pull request by ubergesundheit**
Towards https://github.com/giantswarm/giantswarm/issues/27705

cert-manager-app v2.24.1 contains required changes for upcoming cert-manager-app v3.0.0

This has been tested by changing the App CR + user-override-apps CM

### CODE REVIEW

**Comment by T-Kukawka** [comment]
how about changelog @ubergesundheit ?

**Comment by ubergesundheit** [comment]
> how about changelog @ubergesundheit ?

The one in the README.md of the Release? cert-manager-app is not there currently, but I can add it as a diff from 18.4.2

**Review by Gacko — APPROVED** [review]

**Comment by ubergesundheit** [comment]
@giantswarm/team-phoenix sorry for another ping 
Is this okay now?

**Review by T-Kukawka — APPROVED** [review]

**Comment by T-Kukawka** [comment]
looks good, feel free to merge when u are sure it does not destroy the world nor roll nodes

**Comment by ubergesundheit** [comment]
:crossed_fingers:

**Pull request merged**
