### PR TITLE
CAPI: Request `observability-bundle` v1.9.0.

### PR DESCRIPTION
**Pull request by QuantumEnigmaa**
### Checklist

- [ ] Roadmap issue created
- [ ] Release uses latest stable Flatcar
- [ ] Release uses latest Kubernetes patch version

### Triggering E2E tests

To trigger the E2E test for each new Release added in this PR, add a comment with the following:

`/run releases-test-suites`

If you want to trigger conformance tests, you can do so by adding a comment similar to the following:

`/run conformance-tests PROVIDER=capa RELEASE_VERSION=29.1.0`

For more details see the [README.md](/README.md#running-tests-against-prs).

### CODE REVIEW

**Comment by QuentinBisson** [comment]
Can you also add it into capz and capv?

**Comment by QuantumEnigmaa** [comment]
@QuentinBisson done

**Review by QuentinBisson — APPROVED** [review]

**Comment by QuantumEnigmaa** [comment]
Do I need to specify the `TEST-SUITES` variable ?

**Review by Gacko — CHANGES_REQUESTED** [review]
This is a minor app version bump. We will not deliver such a change in a patch release. See the versioning section in the docs for further details about patch releases: https://intranet.giantswarm.io/docs/product/releases/capi/capi-versioning-scope/#versioning

> The general rule for patch releases is that they have zero impact for customers and do not require rolling nodes. They are used for fixing a problem in the predecessor, temporary mitigations, or other changes that do not require customer action.

Also we already released a CAPA v29.4.0 with Observability Bundle v1.8.0 and the upcoming CAPZ v29.3.0 is aligned to that. Last but not least you forgot vSphere. I'll fix that for you.

> Do I need to specify the TEST-SUITES variable ?

You don't need to run tests for requesting app versions.

**Comment by Gacko** [comment]
See the versioning section in the docs for further details about patch releases: https://intranet.giantswarm.io/docs/product/releases/capi/capi-versioning-scope/#versioning

> The general rule for patch releases is that they have zero impact for customers and do not require rolling nodes. They are used for fixing a problem in the predecessor, temporary mitigations, or other changes that do not require customer action.

**Review by Gacko — APPROVED** [review]

**Comment by QuantumEnigmaa** [comment]
Thx a lot @Gacko ! :muscle:

**Pull request merged**
