### PR TITLE
CAPVCD: Release v28.0.0.

### PR DESCRIPTION
**Pull request by njuettner**
Towards: https://github.com/giantswarm/roadmap/issues/3717

### Checklist

- [x] Roadmap issue created
- [x] Release uses latest stable Flatcar
- [x] Release uses latest Kubernetes patch version

### Triggering E2E tests

To trigger the E2E test for each new Release added in this PR, add a comment with the following:

`/run releases-test-suites`

If you want to trigger conformance tests, you can do so by adding a comment similar to the following:

`/run conformance-tests PROVIDER=capa RELEASE_VERSION=29.1.0`

For more details see the [README.md](/README.md#running-tests-against-prs).

### CODE REVIEW

**Comment by njuettner** [comment]
Checking ...
`⚠️ No valid Release / Test Suite pairings found!`

**Comment by njuettner** [comment]
/run releases-test-suites TARGET_SUITES=./providers/capvcd/standard TARGET_RELEASES=cloud-director-28.0.0

**Comment by njuettner** [comment]
/run releases-test-suites TARGET_SUITES=./providers/capvcd/upgrade PREVIOUS_RELEASE=27.0.0 TARGET_RELEASES=cloud-director-28.0.0

**Comment by njuettner** [comment]
/run releases-test-suites TARGET_SUITES=./providers/capvcd/upgrade PREVIOUS_RELEASE=27.0.0 TARGET_RELEASES=cloud-director-28.0.0

**Comment by njuettner** [comment]
The rolling node upgrades exceeds the time 900seconds, it might be that's a bit slower to roll the nodes on CAPVCD 😞. I looked into it and it was proceeding but not fast enough

**Comment by njuettner** [comment]
/run releases-test-suites TARGET_SUITES=./providers/capvcd/upgrade PREVIOUS_RELEASE=27.0.0 TARGET_RELEASES=cloud-director-28.0.0

**Comment by Gacko** [comment]
/run releases-test-suites TARGET_SUITES=./providers/capvcd/standard PREVIOUS_RELEASE=27.0.0 TARGET_RELEASES=cloud-director-28.0.0

**Review by Gacko — APPROVED** [review]

**Comment by Gacko** [comment]
/run releases-test-suites TARGET_SUITES=./providers/capvcd/upgrade PREVIOUS_RELEASE=27.0.0 TARGET_RELEASES=cloud-director-28.0.0

**Comment by Gacko** [comment]
/run releases-test-suites TARGET_SUITES=./providers/capvcd/standard PREVIOUS_RELEASE=27.0.0 TARGET_RELEASES=cloud-director-28.0.0

**Comment by Gacko** [comment]
/run releases-test-suites TARGET_SUITES=./providers/capvcd/upgrade PREVIOUS_RELEASE=27.0.0 TARGET_RELEASES=cloud-director-28.0.0

**Comment by vxav** [comment]
/run releases-test-suites TARGET_SUITES=./providers/capvcd/upgrade PREVIOUS_RELEASE=27.0.0 TARGET_RELEASES=cloud-director-28.0.0

**Comment by vxav** [comment]
I got pulled into something else and forgot this was running 🙈 

/run releases-test-suites TARGET_SUITES=./providers/capvcd/upgrade PREVIOUS_RELEASE=27.0.0 TARGET_RELEASES=cloud-director-28.0.0

**Comment by Gacko** [comment]
@vxav: See [Nick's comment](https://github.com/giantswarm/releases/pull/1490#issuecomment-2473969420):
> The rolling node upgrades exceeds the time of 900 seconds and then the timeout hits, it might be that's a bit slower to roll the nodes on CAPVCD 😞. I looked into it and it was proceeding but not fast enough

**Comment by vxav** [comment]
900 sec, I suppose it didn't take into account the new timeout

**Comment by Gacko** [comment]
I _think_ we need to release `cluster-test-suites` and update it in Tekton first.

**Comment by njuettner** [comment]
/run releases-test-suites TARGET_SUITES=./providers/capvcd/upgrade PREVIOUS_RELEASE=27.0.0 TARGET_RELEASES=cloud-director-28.0.0

**Comment by njuettner** [comment]
/run releases-test-suites TARGET_SUITES=./providers/capvcd/upgrade PREVIOUS_RELEASE=27.0.0 TARGET_RELEASES=cloud-director-28.0.0

**Comment by Gacko** [comment]
Finally! Wow, it so pretty! 😄

Can we merge and rebase the v29.0.0 branch on `master` then? @giantswarm/team-rocket @giantswarm/team-tenet

**Comment by Gacko** [comment]
/run releases-test-suites PREVIOUS_RELEASE=27.0.0 TARGET_RELEASES=cloud-director-28.0.0

**Comment by njuettner** [comment]
@giantswarm/team-rocket I think we're ready here. PTAL 🙂

**Comment by Gacko** [comment]
/run releases-test-suites PREVIOUS_RELEASE=27.0.0 TARGET_RELEASES=cloud-director-28.0.0

**Review by vxav — APPROVED** [review]
LGTM

**Pull request merged**
