### PR TITLE
deactivate AWS v11.0.1

### PR DESCRIPTION
**Pull request by xh3b4sd**
As discussed in https://gigantic.slack.com/archives/C7865GLSY/p1586723962074000 it looks like we can certainly deprecate `v11.0.1` since it does not make much sense to let users still create Tenant Clusters using the Calico CNI. There are stable releases using the AWS CNI.

### CODE REVIEW

**Comment by xh3b4sd** [comment]
I would also like to get approvals from @paurosello and @marians in case this is fine.

**Comment by paurosello** [comment]
Sure, that sounds good but would like to manage the default PodCIDR in all installations first

**Comment by xh3b4sd** [comment]
What is the ETA for that? How can I help with that?

**Comment by xh3b4sd** [comment]
@paurosello can you answer my comment above? Where are we?

**Comment by paurosello** [comment]
In Adidas and Shutterstock it has not been decided which IP CIDR will be used, and AWS CNI cluster creation is not possible there yet.

So we need to hold this for a while until this customers are able to use the AWS CNI release.

**Comment by xh3b4sd** [comment]
Sure thing. Question was the ETA.

**Comment by xh3b4sd** [comment]
@paurosello as discussed please check with the SEs and let's get this merged.

**Pull request merged**
