### PR TITLE
Add azure release 16.1.0

### PR DESCRIPTION
**Pull request by whites11**
New azure release 16.1.0

### CODE REVIEW

**Comment by MarcelMue** [comment]
@ljakimczuk Maybe you can convince @whites11 to include the new app-operator version here :grimacing:

**Comment by whites11** [comment]
> @ljakimczuk Maybe you can convince @whites11 to include the new app-operator version here grimacing

5.3.1 I guess

**Comment by MarcelMue** [comment]
> > @ljakimczuk Maybe you can convince @whites11 to include the new app-operator version here grimacing
> 
> 5.3.1 I guess

You are correct & my hero

**Comment by whites11** [comment]
azure cncf test is green

**Comment by whites11** [comment]
I found out that cluster operator legacy is reconciling azureclusterconfig CRs even if they are tagged with the cluster operator version label. This is making cluster deletion to fail.

**Review by njuettner — APPROVED** [review]
lgtm

**Review by T-Kukawka — APPROVED** [review]
🚀

**Pull request merged**
