### PR TITLE
Add AWS release v17.2.1

### PR DESCRIPTION
**Pull request by kubasobon**
Towards https://github.com/giantswarm/giantswarm/issues/22569

### CODE REVIEW

**Comment by whites11** [comment]
17.2.0 was released yesterday!!!!!!!!!!!
I thought 6.0.1 was a fixed version of app operator.
Why do we need yet another release?

**Comment by kubasobon** [comment]
Ok, it was brought to my attention that older versions of `app-operator` have some deficiencies. Based on the conversation, I thought I was supposed to prepare this patch release with `v6.0.1`. I was not aware we were still in the process of releasing `v17.2.0` - we could have included the version there, and @pipo02mix tested it apparently.

I understand your frustration @whites11. I think I just misunderstood the whole thing, and now the chance to include the update went out the window. 

I'll close the PR.

**Comment by whites11** [comment]
> Ok, it was brought to my attention that older versions of `app-operator` have some deficiencies. Based on the conversation, I thought I was supposed to prepare this patch release with `v6.0.1`. I was not aware we were still in the process of releasing `v17.2.0` - we could have included the version there, and @pipo02mix tested it apparently.
> 
> I understand your frustration @whites11. I think I just misunderstood the whole thing, and now the chance to include the update went out the window.
> 
> I'll close the PR.

It's me not understanding now :sweat_smile: 
Is 6.0.1 buggy? and 6.1.0 solves the bug?

**Comment by kubasobon** [comment]
I am not 100%, but I think Fer found some issues in `v5` line used in `v17.2.0` releases and he wanted to make it better bringing app-operator to latest.
Let's do it in https://github.com/giantswarm/releases/pull/1005 though :smile:

**Pull request closed without merging**
