### PR TITLE
activate release 11.0.1

### PR DESCRIPTION
**Pull request by xh3b4sd**
This activates `11.0.1`, and deactivates `11.0.0` and `10.1.2`.

### CODE REVIEW

**Comment by calvix** [comment]
should 11.0.0 be set to not active?

**Comment by xh3b4sd** [comment]
Good point. Sorted.

**Comment by xh3b4sd** [comment]
What about the active `10.x.x`release? I understood it is broken as well but this has the other Kubernetes version. Should it be deactivated as well?

**Comment by teemow** [comment]
just check if there are clusters running with this release. you can talk to the responsible SE and ask if there is an upgrade planned. If there are no important clusters you can deactivate it. If there is a problem why customers are not upgrading you might need to consider a patch release for 10.x too.

**Comment by xh3b4sd** [comment]
Checked with @giantswarm/se and deactivated `10.1.2`. We help customers move to `11.x.x` and in case a patch for `10.x.x` is necessary we deliver it separately. This does not seem to be necessary but we did not get feedback on all clusters. We are moving now.

**Pull request merged**
