### PR TITLE
 AWS (CAPA) v27.0.0

### PR DESCRIPTION
**Pull request by weseven**
K8s 1.27+ needs to use cluster chart 0.33.1 due to the removal of in-tree providers (see [related PR fix](https://github.com/giantswarm/cluster/pull/242)).

## Diff

**App diffs**

| app \ release | v26.0.0 | v27.0.0 | change |
| --- | --- | --- | --- |
| cloud-provider-aws | 1.26.11-gs1  | 1.27.7-gs1 | **minor** |

**Component diffs**

| component \ release | v26.0.0 | v27.0.0 | change |
| --- | --- | --- | --- |
| kubernetes | 1.26.15 | 1.27.14 | **minor** |
| cluster-aws | 1.0.0  | 1.0.1| **patch** |

### CODE REVIEW

**Comment by AverageMarcus** [comment]
Ok, lets try that again...

/run releases-test-suites

**Review by yulianedyalkova — APPROVED** [review]

**Comment by AverageMarcus** [comment]
👋  Just using this PR to test triggering conformance tests, ignore me :) 

/run conformance-tests RELEASE_VERSION=v27.0.0

**Comment by AverageMarcus** [comment]
Ah damn, I need to specify the provider also 🤦 

/run conformance-tests RELEASE_VERSION=v27.0.0 PROVIDER=capa

**Comment by yulianedyalkova** [comment]
I was just wondering where the CNCF thing came from :D I will be merging this one, can you use the v28 PR?

**Comment by AverageMarcus** [comment]
@yulianedyalkova Sure thing! I seem to have some more changes to the pipeline that I need to make anyway

**Pull request merged**
