### PR TITLE
Define and activate AWS 12.1.2 platform release

### PR DESCRIPTION
**Pull request by sslavic**
Towards https://github.com/giantswarm/giantswarm/issues/12859

### CODE REVIEW

**Comment by sslavic** [comment]
Tested on ginger:
- 12.1.2 cluster creation
- upgrade from 12.1.1 to 12.1.2
- upgrade from 11.5.2 to 12.1.2

Release is ready to be shipped as soon as release notes and announcements are ready.

**Review by cokiengchiara — APPROVED** [review]
Release notes look good to me. As is our current process, will not immediately announce this but include it in this week's batched announcement on Friday.

**Comment by cokiengchiara** [comment]
> Release notes look good to me. As is our current process, will not immediately announce this but include it in this week's batched announcement on Friday.

After back and forth, for now, agreed in #chapter-product to make immediate announcement w one liner.

**Review by cokiengchiara — APPROVED** [review]
LGTM.

**Pull request merged**
