### PR TITLE
CAPV: Release v28.0.1.

### PR DESCRIPTION
**Pull request by Gacko**

### CODE REVIEW

**Comment by njuettner** [comment]
/run releases-test-suites TARGET_SUITES=./providers/vsphere/standard

**Comment by njuettner** [comment]
run releases-test-suites

**Comment by Gacko** [comment]
/run releases-test-suites TARGET_SUITES=./providers/capv/standard TARGET_RELEASES=vsphere-28.0.1

**Comment by Gacko** [comment]
/run releases-test-suites TARGET_SUITES=./providers/capv/standard TARGET_RELEASES=vsphere-28.0.1

**Comment by Gacko** [comment]
/run releases-test-suites TARGET_SUITES=./providers/capv/standard TARGET_RELEASES=vsphere-28.0.1

**Comment by Gacko** [comment]
/run releases-test-suites TARGET_SUITES=./providers/capv/upgrade PREVIOUS_RELEASE=27.0.1 TARGET_RELEASES=vsphere-28.0.1

**Pull request merged**
